"""
Django settings for ecom_prj project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from environs import Env
from django.contrib import messages

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='')
if not SECRET_KEY:
    raise ValueError('SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['asco.kg', 'www.asco.kg'])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://asco.kg', 'https://www.asco.kg'])
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Referrer / Permissions / CSP — задаются для всех режимов; CSP можно оставить пустым до настройки фронта.
SECURE_REFERRER_POLICY = env(
    "SECURE_REFERRER_POLICY", default="strict-origin-when-cross-origin"
)
PERMISSIONS_POLICY = env(
    "PERMISSIONS_POLICY",
    default="geolocation=(), microphone=(), camera=(), payment=()",
)
SECURE_CONTENT_SECURITY_POLICY = (
    env("SECURE_CONTENT_SECURITY_POLICY", default="") or ""
).strip()
SECURE_CONTENT_SECURITY_POLICY_REPORT_ONLY = env.bool(
    "SECURE_CONTENT_SECURITY_POLICY_REPORT_ONLY", default=False
)

# Application definition
INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',

    'corsheaders',
    'userauths.apps.UserauthsConfig',
    'store',
    'orders',
    'vendor',
    'customer',
    'blog',

    'django_ckeditor_5',
    'anymail',
    'captcha',
    'django_extensions'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'ecom_prj.abuse_middleware.ApiRequestBodySizeLimitMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ecom_prj.abuse_middleware.ApiUserRateLimitMiddleware',
    'userauths.middleware.RequireLoginForAppPrefixesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'ecom_prj.security_audit_middleware.SecurityAuditMiddleware',
    'ecom_prj.security_headers_middleware.ExtraSecurityHeadersMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'store.context.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom_prj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# В production: хост БД только в private network / VPC; не открывайте PostgreSQL в интернет.
# Managed-PostgreSQL (Supabase/RDS и т.д.): включите автобэкапы в панели провайдера; секреты — из env хостинга.

if env.bool('USE_SQLITE', default=False):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME', default='ascodb'),
            'USER': env('DB_USER', default='ascouser'),
            'PASSWORD': env('DB_PASSWORD', default=''),
            'HOST': env('DB_HOST', default='db'),
            'PORT': env('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }

# Preview / CI: не подключать продакшн-БД (Vercel preview, Railway preview и т.д.).
# Секреты только из переменных окружения хостинга (Vercel Env, Railway Variables, Vault и т.д.), не из кода.
_PREVIEW_DEPLOY = (
    env.bool("PREVIEW_DEPLOYMENT", default=False)
    or (env("VERCEL_ENV", default="").strip() == "preview")
    or (env("RAILWAY_ENVIRONMENT", default="").strip().lower() == "preview")
)
if (
    _PREVIEW_DEPLOY
    and not DEBUG
    and not env.bool("USE_SQLITE", default=False)
    and env.bool("BLOCK_PREVIEW_PRODUCTION_DB", default=True)
):
    from django.core.exceptions import ImproperlyConfigured

    _prod_marker = env("PRODUCTION_DATABASE_NAME", default="ascodb")
    _current_name = str(DATABASES["default"].get("NAME") or "")
    if _current_name == str(_prod_marker) and not env.bool(
        "ALLOW_PREVIEW_USE_PRODUCTION_DB", default=False
    ):
        raise ImproperlyConfigured(
            "Preview-деплой не должен использовать продакшн-имя БД. "
            "Задайте отдельный DB_NAME / DATABASE_URL для preview или ALLOW_PREVIEW_USE_PRODUCTION_DB=1 (не рекомендуется)."
        )

# CORS: только явные origin из окружения; wildcard запрещён (см. deploy-check asco.security.W002).
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    x.strip()
    for x in env.list("CORS_ALLOWED_ORIGINS", default=[])
    if x.strip()
]
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)

# Разрешить хост БД в публичной сети (осознанно; иначе deploy-check предупредит)
DATABASE_ALLOW_PUBLIC_HOST = env.bool("DATABASE_ALLOW_PUBLIC_HOST", default=False)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Argon2 — основной алгоритм для новых паролей; PBKDF2/BCrypt — для уже сохранённых хешей (апгрейд при логине).
# MD5/SHA1 как хранение паролей не используются.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Срок жизни ссылки сброса пароля и токенов на базе PasswordResetTokenGenerator (в т.ч. verify-email), сек.
# После успешной смены пароля токен становится недействителен (в хеш входит password field).
PASSWORD_RESET_TIMEOUT = 3600

# Session lifetime (explicit); logout() flushes the session server-side.
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=60 * 60 * 24 * 14)  # 14 days
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = False

# django-ratelimit считает попытки входа в этом кэше. В production с несколькими
# воркерами gunicorn используйте общий Redis (REDIS_URL), иначе лимит «5/мин» действует отдельно на каждый процесс.
_redis_url = (env('REDIS_URL', default='') or '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'asco-auth-ratelimit',
        }
    }

# Public self-registration: requires working email (see register_view). New users stay inactive until email is verified.
REGISTRATION_ENABLED = env.bool('REGISTRATION_ENABLED', default=False)

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')
SERVER_EMAIL = env('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = env('TIME_ZONE', default='Asia/Bishkek')

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Загрузки: до 10 МБ на запрос (поля multipart + тело). Для JSON API см. middleware (1 МБ).
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

AUTH_USER_MODEL = 'userauths.User'

SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# Платежи: только переменные окружения (см. .env.example). Секреты не в клиентских шаблонах.
STRIPE_PUBLIC_KEY = (env("STRIPE_PUBLIC_KEY", default="") or "").strip()
STRIPE_SECRET_KEY = (env("STRIPE_SECRET_KEY", default="") or "").strip()
PAYPAL_CLIENT_ID = (env("PAYPAL_CLIENT_ID", default="") or "").strip()
PAYPAL_SECRET_ID = (env("PAYPAL_SECRET_ID", default="") or "").strip()
FLUTTERWAVE_PUBLIC_KEY = (env("FLUTTERWAVE_PUBLIC_KEY", default="") or "").strip()
FLUTTERWAVE_PRIVATE_KEY = (env("FLUTTERWAVE_PRIVATE_KEY", default="") or "").strip()
PAYSTACK_PUBLIC_KEY = (env("PAYSTACK_PUBLIC_KEY", default="") or "").strip()
PAYSTACK_PRIVATE_KEY = (env("PAYSTACK_PRIVATE_KEY", default="") or "").strip()
RAZORPAY_KEY_ID = (env("RAZORPAY_KEY_ID", default="") or "").strip()
RAZORPAY_KEY_SECRET = (env("RAZORPAY_KEY_SECRET", default="") or "").strip()
# Secret hash из кабинета Flutterwave (вебхуки / redirect с заголовком Verif-Hash), опционально
FLUTTERWAVE_SECRET_HASH = (env("FLUTTERWAVE_SECRET_HASH", default="") or "").strip()

# Вебхуки (подпись / проверка через API)
STRIPE_WEBHOOK_SECRET = (env("STRIPE_WEBHOOK_SECRET", default="") or "").strip()
# ЮKassa: проверка уведомления запросом GET /v3/payments/{id} (shopId + секретный ключ API)
YOOKASSA_SHOP_ID = (env("YOOKASSA_SHOP_ID", default="") or "").strip()
YOOKASSA_SECRET_KEY = (env("YOOKASSA_SECRET_KEY", default="") or "").strip()
TELEGRAM_WEBHOOK_SECRET = (env("TELEGRAM_WEBHOOK_SECRET", default="") or "").strip()

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Обратная совместимость с кодом, ожидающим settings.FROM_EMAIL
FROM_EMAIL = (env("FROM_EMAIL", default="") or "").strip() or DEFAULT_FROM_EMAIL

ANYMAIL = {
    "MAILGUN_API_KEY": (env("MAILGUN_API_KEY", default="") or "").strip(),
    "MAILGUN_SENDER_DOMAIN": (env("MAILGUN_SENDER_DOMAIN", default="") or "").strip(),
}

# Telegram Bot: уведомления о новых заказах
TELEGRAM_BOT_TOKEN = (env("TELEGRAM_BOT_TOKEN", default="") or "").strip()
_raw_tg_chat = env("TELEGRAM_CHAT_ID", default="")
# ID группы/чата может быть int (-100...) — API принимает строку или число
TELEGRAM_CHAT_ID = (
    ""
    if _raw_tg_chat is None or _raw_tg_chat == ""
    else str(_raw_tg_chat).strip()
)

# Лимиты API (django-ratelimit + кэш; при нескольких воркерах задайте REDIS_URL).
API_RATE_LIMIT = env("API_RATE_LIMIT", default="100/m")
API_MAX_REQUEST_BODY_BYTES = env.int("API_MAX_REQUEST_BODY_BYTES", default=1024 * 1024)
API_RATE_LIMIT_PATH_PREFIXES = (
    "/api/",
    "/filter_products/",
    "/search_suggestions/",
    "/add_to_cart/",
    "/delete_cart_item/",
    "/customer/sync_wishlist_from_storage/",
    "/customer/toggle_wishlist/",
    "/customer/add_to_wishlist/",
    "/customer/remove_from_wishlist/",
    "/customer/mark_noti_seen/",
    "/vendor/delete_variants/",
    "/vendor/delete_variants_items/",
    "/vendor/delete_product_image/",
)
API_RATE_LIMIT_PATH_REGEXES = (
    r"^/checkout/[^/]+/update_phone/$",
    r"^/stripe_payment/[^/]+/$",
    r"^/vendor/delete_product/\d+/$",
)

# AI (см. store/api_views.ai_generate)
AI_GENERATION_LIMIT_FREE_PER_DAY = env.int("AI_GENERATION_LIMIT_FREE_PER_DAY", default=5)
AI_GENERATION_LIMIT_PRO_PER_DAY = env.int("AI_GENERATION_LIMIT_PRO_PER_DAY", default=50)
AI_QUOTA_CACHE_TTL = env.int("AI_QUOTA_CACHE_TTL", default=86400)

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

GRAPH_MODELS = {
    'all_applications': True,
    'graph_models': True,
}

LOGIN_URL = "userauths:sign-in"
LOGIN_REDIRECT_URL = ""
LOGOUT_REDIRECT_URL = "userauths:sign-in"

# RECAPTCHA_PUBLIC_KEY = env("DJANGO_RECAPTCHA_PUBLIC_KEY")
# RECAPTCHA_PRIVATE_KEY = env("DJANGO_RECAPTCHA_PRIVATE_KEY")

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Пороги аудита (middleware)
SECURITY_DENIED_PER_IP_THRESHOLD = env.int("SECURITY_DENIED_PER_IP_THRESHOLD", default=30)
SECURITY_DENIED_WINDOW_SEC = env.int("SECURITY_DENIED_WINDOW_SEC", default=300)
SECURITY_REQUESTS_PER_MINUTE_ANOMALY = env.int(
    "SECURITY_REQUESTS_PER_MINUTE_ANOMALY", default=500
)

# Локальный файл логов; LOG_TO_FILE=false — только stdout (удобно для Docker / read-only FS).
_LOG_HANDLERS = ["console", "file"]
if not env.bool("LOG_TO_FILE", default=True):
    _LOG_HANDLERS = ["console"]
else:
    try:
        (BASE_DIR / "logs").mkdir(parents=True, exist_ok=True)
    except OSError:
        _LOG_HANDLERS = ["console"]

_LOG_HANDLER_DEFS = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
    'security_stream': {
        'class': 'logging.StreamHandler',
        'formatter': 'asco_json',
    },
}
if 'file' in _LOG_HANDLERS:
    _LOG_HANDLER_DEFS['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'django.log',
        'maxBytes': 1024 * 1024 * 10,  # 10 MB
        'backupCount': 5,
        'formatter': 'verbose',
    }

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'asco_json': {
            '()': 'ecom_prj.structured_security.AscoJsonFormatter',
            'format': '%(level)s %(name)s %(message)s',
        },
    },
    'handlers': _LOG_HANDLER_DEFS,
    'root': {
        'handlers': _LOG_HANDLERS,
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': _LOG_HANDLERS,
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': _LOG_HANDLERS,
            'level': 'WARNING',
            'propagate': False,
        },
        'asco.security': {
            'handlers': ['security_stream'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Custom Admin Settings
JAZZMIN_SETTINGS = {
    "site_title": "ASCO.KG",
    "site_header": "ASCO.KG",
    "site_brand": "ASCO.KG",
    # "site_icon": "images/favicon.ico",
    # "site_logo": "images/logos/logo.jpg",
    "welcome_sign": "Welcome To Desphixs",
    "copyright": "Desphixs",
    "user_avatar": "images/photos/logo.jpg",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "store",
        "store.product",
        "store.cartorder",
        "store.cartorderitem",
        "store.cart",
        "store.category",
        "store.brand",
        "store.productfaq",
        "store.review",
        "vendor.Coupon",
        "vendor.DeliveryCouriers",
        "userauths",
        "userauths.user",
        "userauths.profile",
        "donations",
        "blog",
        'newsfeed',
        "contacts",
        "addon",
    ],
    "icons": {
        "admin.LogEntry": "fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "userauths.User": "fas fa-user",
        "userauths.Profile": "fas fa-address-card",

        "donations.Donation": "fas fa-hand-holding-usd",
        "donations.Payment": "fas fa-credit-card",

        "newsfeed.Newsletter": "fas fa-envelope",
        "newsfeed.SubscribedUser": "fas fa-at",

        "newsfeed.SubscribedUser": "fas fa-at",

        "contacts.Inquiry": "fas fa-phone",
        "addon.BasicAddon": "fas fa-cog",

        "store.Product": "fas fa-th",
        "store.CartOrder": "fas fa-shopping-cart",
        "store.Cart": "fas fa-cart-plus",
        "store.CartOrderItem": "fas fa-shopping-basket",
        "store.Brand": "fas fa-check-circle",
        "store.productfaq": "fas fa-question",
        "store.Review": "fas fa-star fa-beat",
        "store.Category": "fas fa-tag",
        "store.Tag": "fas fa-tag",
        "store.Notification": "fas fa-bell",

        "customer.Address": "fas fa-location-arrow",
        "customer.Wishlist": "fas fa-heart",

        "vendor.DeliveryCouriers": "fas fa-truck",
        "vendor.Coupon": "fas fa-percentage",
        "vendor.Vendor": "fas fa-store",
        "vendor.Notification": "fas fa-bell",
        "vendor.PayoutTracker": "fas fa-wallet",
        "vendor.ChatMessage": "fas fa-envelope",

        "addons.BecomeAVendor": "fas fa-user-plus",
        "addons.AboutUS": "fas fa-users",
        "addons.Company": "fas fa-university",
        "addons.BasicAddon": "fas fa-cog",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    "related_modal_active": False,

    "custom_js": None,
    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload"
        ],
    },
    "comment": {
        "language": {"ui": "ru", "content": "ru"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "en",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": [
            # "heading",
            # "codeBlock",
            # "|",
            # "outdent",
            # "indent",
            # "|",
            "bold",
            "italic",
            "underline",
            "|",
            "link",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
    },
}
