# Generated by Django 4.2 on 2025-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactmessage_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Сообщение или Обращение'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Профили'},
        ),
    ]
