# Generated by Django 4.2 on 2025-11-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_contactmessage_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Vendor', 'Продавец'), ('Customer', 'Покупатель')], default=None, max_length=255, null=True),
        ),
    ]
