# Generated by Django 4.2 on 2025-11-10 15:49

from django.db import migrations, models


def forwards(apps, schema_editor):
    Profile = apps.get_model("userauths", "Profile")
    User = apps.get_model("userauths", "User")

    Profile.objects.filter(user_type__in=["Vendor", "vendor"]).update(user_type="manager")
    Profile.objects.filter(user_type__in=["Customer", "customer", "", None]).update(user_type="guest")

    for user in User.objects.filter(is_superuser=True):
        full_name = f"{getattr(user, 'first_name', '')} {getattr(user, 'last_name', '')}".strip() or user.email
        profile, created = Profile.objects.get_or_create(
            user=user,
            defaults={
                "user_type": "superadmin",
                "full_name": full_name,
            },
        )
        if not created:
            updated = False
            if profile.user_type != "superadmin":
                profile.user_type = "superadmin"
                updated = True
            if not profile.full_name:
                profile.full_name = full_name
                updated = True
            if updated:
                profile.save(update_fields=["user_type", "full_name"])


def backwards(apps, schema_editor):
    Profile = apps.get_model("userauths", "Profile")

    Profile.objects.filter(user_type="manager").update(user_type="Vendor")
    Profile.objects.filter(user_type="guest").update(user_type="Customer")
    Profile.objects.filter(user_type="superadmin").update(user_type="Vendor")


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_alter_profile_user_type"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "Гость"),
                    ("manager", "Менеджер"),
                    ("superadmin", "Суперадмин"),
                ],
                default="guest",
                max_length=50,
                null=True,
            ),
        ),
    ]
