# Generated by Django 4.2 on 2025-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена до скидки', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сколько клиент сэкономит', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Итоговая сумма без учёта скидки', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сумма, сэкономленная покупателем', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендовано на маркетплейсе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Обычная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название варианта'),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название'),
        ),
    ]
