# Generated by Django 4.2 on 2025-11-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Корзина'},
        ),
    ]
