# Generated by Django 4.2 on 2025-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Галлереи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='variantitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Варианты товара'},
        ),
    ]
