# Generated by Django 4.2 on 2025-11-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_cart_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Заказы продукта'},
        ),
    ]
