# Generated by Django 4.2 on 2025-11-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    OrderItem = apps.get_model("store", "OrderItem")
    Product = apps.get_model("store", "Product")

    legacy_to_new = {
        "Pending": "new",
        "Processing": "processing",
        "Shipped": "shipped",
        "Fulfilled": "delivered",
        "Cancelled": "cancelled",
    }

    valid_order_statuses = {choice for choice, _ in Order._meta.get_field("status").choices}
    valid_item_statuses = {choice for choice, _ in OrderItem._meta.get_field("status").choices}

    for order in Order.objects.all():
        if order.status in legacy_to_new:
            order.status = legacy_to_new[order.status]
        elif order.status not in valid_order_statuses:
            order.status = "new"

        if order.status_changed_at is None:
            order.status_changed_at = order.date
        if order.status != "cancelled":
            order.cancel_comment = order.cancel_comment or ""
        elif not order.cancel_comment:
            order.cancel_comment = "Отмена зафиксирована до миграции статусов"

        order.save(update_fields=["status", "status_changed_at", "cancel_comment"])

    for item in OrderItem.objects.all():
        if item.status in legacy_to_new:
            item.status = legacy_to_new[item.status]
        elif item.status not in valid_item_statuses:
            item.status = "new"
        item.save(update_fields=["status"])

    for product in Product.objects.filter(created_by__isnull=True):
        product.created_by = product.vendor
        product.save(update_fields=["created_by"])


def backwards(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    OrderItem = apps.get_model("store", "OrderItem")

    new_to_legacy = {
        "new": "Pending",
        "processing": "Processing",
        "assembled": "Processing",
        "shipped": "Shipped",
        "delivered": "Fulfilled",
        "cancelled": "Cancelled",
    }

    for order in Order.objects.all():
        order.status = new_to_legacy.get(order.status, "Pending")
        order.save(update_fields=["status"])

    for item in OrderItem.objects.all():
        item.status = new_to_legacy.get(item.status, "Pending")
        item.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0019_alter_orderitem_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_status",
            new_name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="cancel_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_status_changed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("assembled", "Собран"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("assembled", "Собран"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
