# Generated by Django 4.2 on 2025-11-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_remove_order_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Оплачено"),
                    ("Processing", "После доставки будет оплачено"),
                    ("Unpaid", "Не оплачено"),
                    ("Failed", "Ошибка оплаты"),
                ],
                default="Processing",
                max_length=100,
            ),
        ),
    ]
