# Generated by Django 4.2.16 on 2026-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', help_text='Отображается в блоке «Популярные категории» на главной.', null=True, upload_to='images'),
        ),
    ]
