/**
 * PurgeCSS для Django (абсолютные пути — иначе CLI дублирует путь к output).
 * Запуск из корня проекта: npx purgecss --config purgecss.config.js
 */
const path = require('path');
const root = path.resolve(__dirname);

module.exports = {
    content: [
        `${root}/templates/**/*.html`.replace(/\\/g, '/'),
        `${root}/static/**/*.js`.replace(/\\/g, '/'),
    ],
    css: [path.join(root, 'static', 'assets', 'css', 'styles.min.css')],
    output: path.join(root, 'static', 'assets', 'css'),
    safelist: {
        standard: [
            /^tw-/,
            /^modal/,
            /^fade/,
            /^show/,
            /^btn/,
            /^nav/,
            /^dropdown/,
            /^collapse/,
            /^slick/,
            /^irs/,
            /^fa-/,
            /^fab/,
            /^fas/,
            /^far/,
            /^bi-/,
            /^theme/,
            /^footer/,
            /^header/,
            /^navigation/,
            /^dark-footer/,
            /^skin-/,
            /^container/,
            /^row/,
            /^col/,
            /^alert/,
            /^card/,
            /^breadcrumb/,
            /^pagination/,
            /^offcanvas/,
            /^spinner/,
            /^owl-/,
            /^explore-/,
            /^sec_/,
            /^middle/,
            /^gray/,
            /^position-/,
            /^text-/,
            /^bg-/,
            /^border/,
            /^rounded/,
            /^shadow/,
            /^img-/,
            /^list-/,
            /^form-/,
            /^input/,
            /^table/,
            /^badge/,
            /^ft-/,
            /^fs-/,
            /^ht-/,
            /^lh-/,
            /^lead/,
            /^circle/,
            /^progress/,
            /^full-/,
            /^no-/,
            /^ab-/,
            /^line-/,
            /^br-/,
            /^bb-/,
            /^bt-/,
            /^bl-/,
            /^b-/,
            /^dn/,
            /^tbl/,
            /^shop/,
            /^product/,
            /^cart/,
            /^checkout/,
            /^swiper/,
            /^is-/,
            /^has-/,
        ],
        deep: [/tooltip/, /popover/, /active/, /open/, /carousel/, /accordion/],
    },
};
