# Generated by Django 4.2 on 2025-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Адреса Клиентов'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Избранные'},
        ),
    ]
