# Generated by Django 4.2 on 2025-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Категории блога'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Комментарии'},
        ),
    ]
